### ISSUE TITLE
Improve docs (Contributing.md)

### ISSUE THREAD

**Issue by ayushsarode** [ayushsarode/Xypo-LearningApp#97]
improve ```contributing.md```, make it minimalistic  and remove hacktoberfest section.

**Comment by Odin5133** [comment]
Can you assign this issue to me?
Main task- making contributing.md minimalistic and more general

**Comment by Apoorv012** [comment]
Hey @ayushsarode I would like to work on this issue. Could you please assign me?

**Comment by ayushsarode** [comment]
Sure!

**Comment by Odin5133** [comment]
Hey 👋 @ayushsarode . A maintainer needs to add hacktoberfest-accepted label to the PR/MR or to the issue for a repo to be participating in hacktoberfest. So can you please add that 😅
